### ISSUE TITLE
TO-DO list 

### ISSUE THREAD

**Issue by RenatoCesarF** [RenatoCesarF/Auto-Reddit-Video#1]
## Generator  Robot (Informant)
- [x] get reddit data
- [x] clean up mk from post 
- [x] generate speech with title and content post
- [ ] organize how the post and response is saved (redis)
- [ ] get post reply based in trending and if was already used 
- [ ] move server to AWS
- [ ] save audios in a bucket (somehow)
- [ ] create rote to delete already used audios
-----
## Render Robot (producer)
- [x] get post data
- [x] get reply data
- [x] recreate  reddit post component
- [x] recreate reddit reply component
- [x] render video with audio
- [x] sync post video and response video with their audios
- [x] fix jiggle
- [x] #5
- [x] #8
- [ ] "subscribe" sequence
- [ ] upload  video
-----
## Publisher Robot
- [ ] Receive video properly (maybe though API call)
- [ ] get access to TikTok API
- [ ] get access to youtube API
- [ ] #10
- [ ] publish in tiktok
- [ ] if upload, save in redis that this id of post and reply was already used
- [ ] Call API to delete video from bucket
- [ ] call API to delete audio form bucket
